version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    #   MONGO_INITDB_DATABASE: mydb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
